# This is a basic workflow to help you get started with Actions

name: Mission File Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Pull Liberation Tools
        run: |
          cd ..
          mkdir lib
          cd lib
          git init
          git remote add origin https://github.com/KillahPotatoes/KP-Liberation.git
          git fetch
          git pull origin master
          cd _tools
          npm i
          npm i -g gulp gulp-cli
          
