# This is a basic workflow to help you get started with Actions

name: Mission File Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Pull Liberation Tools
        run: |
          cd ..
          mkdir lib
          cd lib
          git init
          git remote add origin https://github.com/KillahPotatoes/KP-Liberation.git
          git fetch
          git pull origin master
          cd _tools
          npm install
          
      - name: Setup Build Enviroment
        run: |
          cd ..
          mkdir Missionframework
          mkdir Missionbasefiles
          cd lib
          mkdir build
          cd ..
          xcopy 501st-Liberation\Framework Missionframework /E
          xcopy 501st-Liberation\Mission_Base Missionbasefiles /E
          cp 501st-Liberation\Config\presets.json lib\presets.json
          cd lib
          ls
          
      - name: Run Build
        run: |
          cd ..\lib
          npm install gulp
          npx gulp build
          npx gulp pbo
          
      - name: Move PBOs
        run: |
          cd ..
          xcopy lib\build 501st-Liberation\mpmissions /E/Y
          
      - name: Update Repo
        if: ${{ !env.ACT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Mission File Release
          push_options: '--force'
