# This is a basic workflow to help you get started with Actions

name: Mission File Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Pull Liberation Tools
        run: |
          cd ..
          mkdir lib
          cd lib
          git init
          git remote add origin https://github.com/KillahPotatoes/KP-Liberation.git
          git fetch
          git pull origin master
          
      - name: Setup Build Enviroment
        run: |
          cd ..
          Remove-Item -Recurse -Force -Path lib\Missionframework\*
          xcopy 501st-Liberation\Framework lib\Missionframework /E
          Remove-Item -Recurse -Force -Path lib\Missionbasefiles\*
          xcopy 501st-Liberation\Mission_Base lib\Missionbasefiles /E
          Remove-Item -Force -Path lib\_tools\_presets.json
          cp 501st-Liberation\Config\_presets.json lib\_tools\_presets.json
          
      - name: Run Build
        run: |
          cd ..\lib\_tools
          npm install
          npx gulp build
          npx gulp pbo
          
      - name: Move PBOs
        run: |
          cd ..
          xcopy lib\_tools\build\pbo 501st-Liberation\mpmissions /E/Y
          
      - name: Update Repo
        if: ${{ !env.ACT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Mission File Release
          push_options: '--force'
